### ISSUE TITLE
Question: where is the corpus data

### ISSUE THREAD

**Issue by DonaldTsang** [jonsafari/witch-language#1]
Does this repo have a corpus or does it simply use NLTK's internal library for language detection?

**Comment by jonsafari** [comment]
When you run `nltk.download('udhr2')`, it installs the corpus into `~/nltk_data/corpora/udhr2/`

**Comment by DonaldTsang** [comment]
Got it, UDHR is one of the dataset that I really dislike as it is too short but overly used.
